# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_obj', models.CharField(max_length=200)),
                ('c_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=200)),
                ('p_name', models.CharField(max_length=200)),
                ('p_desc', models.CharField(max_length=200)),
                ('c_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Category')),
            ],
        ),
    ]
