# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=200)),
                ('u_email', models.CharField(max_length=200)),
                ('u_password', models.CharField(max_length=200)),
            ],
        ),
    ]
