# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20190321_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
