# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20190321_1300'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
