# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20190321_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='p_id',
            field=models.CharField(max_length=200),
        ),
    ]
