# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-26 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_by', models.CharField(max_length=200)),
                ('ord_id', models.CharField(max_length=200)),
                ('ord_name', models.CharField(max_length=200)),
                ('ord_desc', models.CharField(max_length=200)),
                ('ord_qty', models.IntegerField()),
            ],
        ),
    ]
