# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustName', models.CharField(max_length=200)),
                ('CustId', models.IntegerField()),
            ],
        ),
    ]
