# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-30 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EId', models.IntegerField()),
                ('EName', models.CharField(max_length=200)),
            ],
        ),
    ]
